import { Metadata } from "next"
import Header from "./components/Header"
import './globals.css'
import GoBackButton from "./components/GoBackButton"

export const metadata: Metadata = {
  title: {
    default: "NextJs Tutorial",
    template: "%s | NextJs Tutorial"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <GoBackButton/>
        <main className="m-4">
          {children}
        </main>
        
        <footer className="text-center text-4xl bg-black text-white p-4 fixed bottom-0 left-0 w-full"> Footer </footer>
      </body>
    </html>
  )
}
